language: java
jdk:
- oraclejdk8
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: a1kjrF7411OgncH1oF73e0UjQhNYBsJQ2Llg9CdyAJUEmL6qjZFiLU2a1FTXAwT5I6qZwiBANrqc9FEHyq6erKONssyU9x66EmVDu4cog22sXmdlf084vci2lgrze9yNHdlQNHO991KB/Gryfl9062qrCHMUZKROzOACX+5Io+/LX1E7REvtYTXUSxXMIOl5Daws+Rzf1Qq3Gm/vi3XADXAJKGF2fbHvROZv8Ca01FOIoNuvkytpekoBlKZiQSntVqwB7WiEJqdqUiMzGYRvf5PDp9qNC1ZhkKHzYTnd2pp36O1g1DwhlT7jpvJeS96xfCA28Tbs1ktTaaZjB4GE9NZapz4dbx3OOlJT72gNHK6MjS+kT6/yB1fOebADTIigSxyrS858Ki6+EA0uUKNm1H8jIBVTP4X6RtbtjJzF5Xy/iuAbh4nIg++aOWeLMsjeE0ZVFKpq4Vvv4jU4xJdrJH9uDu498PQwrW0fdjZTSRbDNwRJMSssL571rOkRmT1Cgsy6SYXVDTZ2OPmYfdbaU2iq8PBnXFMRyDJNCFIFa6WKQyAP4oIW84K8Dq2rU5wsoIBtqaqk8oP9X5zsV14MLUxtH5LvQOW6GzhhwzMnhpj+XSMlSFZxUK7lVN2RKCbLKP5Eo3RI6v7y8UiItPzy7h1r7czZa++b4O7yVAY3bhM=
